# Generated by Django 5.2.17 on 2026-09-15 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('consult', '입소 상담'), ('tour', '견학 신청'), ('volunteer', '자원봉사'), ('donate', '후원')], max_length=20, verbose_name='구분')),
                ('status', models.CharField(choices=[('waiting', '대기'), ('done', '상담 완료'), ('approved', '승인'), ('rejected', '반려')], default='waiting', max_length=20, verbose_name='상태')),
                ('name', models.CharField(max_length=80, verbose_name='이름')),
                ('phone', models.CharField(max_length=30, verbose_name='연락처')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='제목')),
                ('body', models.TextField(blank=True, verbose_name='내용')),
                ('extra', models.JSONField(blank=True, default=dict, verbose_name='부가정보')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='제목')),
                ('image', models.CharField(max_length=200, verbose_name='이미지 경로')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용')),
                ('sort_order', models.PositiveIntegerField(default=1, verbose_name='순서')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, unique=True, verbose_name='코드')),
                ('name', models.CharField(max_length=80, verbose_name='게시판명')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Popup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='제목')),
                ('body', models.TextField(verbose_name='내용')),
                ('is_active', models.BooleanField(default=False, verbose_name='표시')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=80, unique=True, verbose_name='검색어')),
                ('search_count', models.PositiveIntegerField(default=0, verbose_name='검색 횟수')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='추천검색어')),
                ('recommend_order', models.PositiveIntegerField(default=0, verbose_name='추천 순서')),
            ],
            options={
                'ordering': ['-search_count', 'keyword'],
            },
        ),
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='키')),
                ('label', models.CharField(max_length=80, verbose_name='항목명')),
                ('body', models.TextField(blank=True, verbose_name='내용')),
            ],
        ),
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(max_length=300, verbose_name='경로')),
                ('referer', models.CharField(blank=True, max_length=400, verbose_name='유입 경로')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='세션')),
            ],
            options={
                'ordering': ['-visited_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('body', models.TextField(verbose_name='내용')),
                ('author_name', models.CharField(blank=True, max_length=50, verbose_name='작성자')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='상단 고정')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='숨김')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='cms.board')),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50, verbose_name='작성자')),
                ('body', models.TextField(verbose_name='내용')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='숨김')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='cms.post')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
