# Generated by Django 5.2.17 on 2026-09-16 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_post_image_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='popup',
            name='image',
            field=models.CharField(blank=True, max_length=300, verbose_name='이미지'),
        ),
        migrations.AlterField(
            model_name='popup',
            name='body',
            field=models.TextField(blank=True, verbose_name='내용'),
        ),
        migrations.AlterField(
            model_name='popup',
            name='title',
            field=models.CharField(blank=True, max_length=120, verbose_name='제목'),
        ),
    ]
