# Generated by Django 5.2.17 on 2026-09-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cms", "0004_usagestat_waitlistentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyMenu",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(unique=True, verbose_name="날짜")),
                ("breakfast", models.CharField(blank=True, max_length=400, verbose_name="아침")),
                ("lunch", models.CharField(blank=True, max_length=400, verbose_name="점심")),
                ("dinner", models.CharField(blank=True, max_length=400, verbose_name="저녁")),
                ("snack", models.CharField(blank=True, max_length=400, verbose_name="간식")),
            ],
            options={
                "verbose_name": "일일 식단",
                "verbose_name_plural": "메인 식단",
                "ordering": ["date"],
            },
        ),
    ]
