# Generated by Django 5.2.17 on 2026-09-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('member', '일반 회원'), ('guardian', '보호자'), ('admin', '관리자')], default='member', max_length=20, verbose_name='권한'),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('active', '정상'), ('suspended', '정지'), ('withdrawn', '탈퇴')], default='active', max_length=20, verbose_name='상태'),
        ),
    ]
